[build-system]
requires = ["setuptools>=61.0", "wheel", "maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "hbp100"
version = "3.0.0"
description = "Rust-powered PII extraction for HBP100"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "Dipanjan Dutta", email = "relic.of.sky@gmail.com"}
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[project.dependencies]
pyo3 = "*"

[project.urls]
"Homepage" = "https://github.com/Erox-02/humming-bird-v3"

[tool.maturin]
python-source = "python"
module-name = "hbp100"
manifest-path = "Cargo.toml"
